config:
  enabled: true
  global:
    resolve_timeout: 5m

  route:
    group_interval: 5m
    group_wait: 10s
    repeat_interval: 1h
    receiver: "email-alerts"

  receivers:
    - name: "email-alerts"
      email_configs:
        - to: "kogewev477@getmola.com"
          from: "chinmaykubal12@gmail.com"
          smarthost: "smtp.mailtrap.io:587"

  alerting_rules:
    - alert: MemoryUsageHigh
      expr: (1 - ((node_memory_MemFree + node_memory_Cached) / node_memory_MemTotal)) * 100 > 70
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Memory usage is high"

    - alert: CPUUsageHigh
      expr: (1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100 > 70
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "CPU usage is high"

    - alert: DiskUsageHigh
      expr: (node_filesystem_avail_bytes{fstype=~"ext4|xfs",mountpoint="/"} / node_filesystem_size_bytes{fstype=~"ext4|xfs",mountpoint="/"}) * 100 > 70
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Disk usage is high"
